version: "3.8"
services:
  database:
    container_name: Familydatabase
    image: mysql:8.0
    environment:
      MYSQL_USER: ${MYSQLDB_DOCKER_USER}
      MYSQL_PASSWORD: ${MYSQLDB_DOCKER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_DOCKER_PASSWORD}
    volumes:
      - "db_data:/var/lib/mysql"
      - "./mysql-init:/docker-entrypoint-initdb.d"
    ports:
      - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}"
  familymemberapp:
    # build: ./FamilyMemberApp
    container_name: FamilyMemberApp
    image: dkorb/familymemberapp:latest
    env_file: .env
    ports:
      - "${SPRING_FAMILY_MEMBER_APP_PORT}:${SPRING_FAMILY_MEMBER_APP_PORT}"
    depends_on:
      - database
  familyapp:
    # build: ./FamilyApp
    container_name: FamilyApp
    image: dkorb/familyapp:latest
    env_file: .env
    ports:
      - "${SPRING_FAMILY_APP_PORT}:${SPRING_FAMILY_APP_PORT}"
    depends_on:
      - familymemberapp
volumes:
  db_data: