apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      service: database
  strategy: {}
  template:
    metadata:
      labels:
        service: database
    spec:
      containers:
        - env:
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_USER
              value: user
          image: mysql:8.0
          name: familydatabase
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config
      restartPolicy: Always
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |-
    GRANT ALL PRIVILEGES ON *.* TO 'user'@'%';
    ALTER USER 'user'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
    CREATE DATABASE IF NOT EXISTS familydb;
    CREATE DATABASE IF NOT EXISTS familymemberdb;
