apiVersion: v1
kind: Service
metadata:
  labels:
    service: familymemberapp
  name: familymemberapp
spec:
  ports:
    - port: 8010
      targetPort: 8010
  type: LoadBalancer
  selector:
    service: familymemberapp
