apiVersion: v1
kind: Service
metadata:
  labels:
    service: familyapp
  name: familyapp
spec:
  ports:
    - port: 8020
      targetPort: 8020
  type: LoadBalancer
  selector:
    service: familyapp
